function [ paths ] = altixPaths(  )
%Return paths

clusterRoot='\\komodo\SharedData\Fintan\Jevgenija\CodeRepo\visionlaball\';


%Paths
paths={clusterRoot,[clusterRoot 'matlab-helpers\'],...
    [clusterRoot 'sharePipe'],...
    [clusterRoot 'sockets'],...
    [clusterRoot 'mcgm'],...
    [clusterRoot 'motionTransfer'],...
    [clusterRoot 'common'],...
    [clusterRoot 'incrWarp'],...
    [clusterRoot 'firePCA'],...
    [clusterRoot 'cluster-utils'],...
    [clusterRoot 'tests'],...
    [clusterRoot 'misc-running'],...
    [clusterRoot 'jevTest'],...
    [clusterRoot 'tests\mexfiles']};	
end
