function [ paths ] = altixPaths(  )
%Return paths

clusterRoot='C:\Export\JobData1\VisionLabLibrary\';


%Paths
paths={clusterRoot,[clusterRoot 'Code\matlab-helpers\'],[clusterRoot 'Code\'],...
    [clusterRoot 'Code\sharePipe'],...
    ['C:\Export\JobData1\Jevgenija'],...
    ['C:\Export\JobData1\VisionLabLibrary\Code\rathore\Dev\'],...
    [clusterRoot 'Code\sockets'],...
    [clusterRoot 'Code\mcgm'],...
    [clusterRoot 'Code\motionTransfer'],...
    [clusterRoot 'Code\common'],...
    [clusterRoot 'Code\incrWarp'],...
    [clusterRoot 'Code\firePCA'],...
    [clusterRoot 'Code\cluster-utils'],...
    [clusterRoot 'Code\tests'],...
    [clusterRoot 'Code\misc-running'],...
    [clusterRoot 'tests\mexfiles']};	
end

